import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from '@/modules/auth_provider'
import WebSocketProvider from '@/modules/websocket_provider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <AuthContextProvider>

      <WebSocketProvider>

        <html lang="pt-br">
          <body>
            {children}
          </body>
        </html>

      </WebSocketProvider>

    </AuthContextProvider>
  );
}
